name: Push Docker Image

on:
  push:
    branches:
      - main
      - stage
      - docker-image
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login into Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2

      - name: Get Short SHA
        id: vars
        run: |
          echo ::set-output name=short_sha::$(git rev-parse --short=7 ${{ github.sha }})

      - name: Build the Docker image
        run: |
              docker build --build-arg MIX_ENV=prod \
               --build-arg PG_MAJOR=11 \
               --build-arg NODE_MAJOR=18 \
               --build-arg YARN_VERSION=1.13.0 \
               -t michelson/rauversion \
               .

      - name: Tag and Push Docker image
        if: github.event_name == 'push'
        run: |
          docker tag michelson/rauversion michelson/rauversion:$SHORT_SHA
          docker push michelson/rauversion:$SHORT_SHA
          echo "SHORT_SHA: ${SHORT_SHA}"
        env:
          SHORT_SHA: ${{ steps.vars.outputs.short_sha }}

      - name: Tag LATEST and Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker tag michelson/rauversion michelson/rauversion:latest
          docker push michelson/rauversion:latest
          echo "LATEST deployed!"

      - name: Tag RELEASE and Push Docker image
        if: github.event_name	== 'release'
        run: |
          docker tag michelson/rauversion michelson/rauversion:${{ github.ref_name }}
          docker push michelson/rauversion:${{ github.ref_name }}
          echo "${{ github.ref_name }} deployed!"
